services:
  # ---------- MAIN BACKEND DB ----------
  db-main:
    image: postgres:16
    container_name: db_main
    environment:
      POSTGRES_USER: blog_user
      POSTGRES_PASSWORD: blog_password
      POSTGRES_DB: blog_db
    volumes:
      - db_main_data:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blog_user -d blog_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ---------- USERS DB ----------
  db-users:
    image: postgres:16
    container_name: db_users
    environment:
      POSTGRES_USER: blog_user
      POSTGRES_PASSWORD: blog_password
      POSTGRES_DB: users_db
    volumes:
      - db_users_data:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blog_user -d users_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ---------- REDIS (BROKER) ----------
  redis:
    image: redis:7-alpine
    container_name: redis
    networks:
      - internal
    ports:
      - "6379:6379"

  # ---------- PUSH NOTIFICATOR ----------
  push-notificator:
    image: ghcr.io/ayusavin/push-notification-playground:1.0.0
    container_name: push_notificator
    ports:
      - "8002:8000"
    networks:
      - internal

  # ---------- BACKEND ----------
  backend:
    build: ./backend
    container_name: backend
    env_file:
      - ./backend/.env
    depends_on:
      db-main:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - internal
    expose:
      - "8000"
    ports:
      - "8000:8000"
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ---------- USERS API ----------
  users-api:
    build: ./users_service
    container_name: users_api
    env_file:
      - ./users_service/.env
    depends_on:
      db-users:
        condition: service_healthy
    networks:
      - internal
    expose:
      - "8000"
    ports:
      - "8001:8000"
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./users_service/migrations:/app/migrations
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ---------- WORKER ----------
  worker:
    build: ./worker
    container_name: worker
    env_file:
      - ./worker/.env
    depends_on:
      redis:
        condition: service_started
      push-notificator:
        condition: service_started
    networks:
      - internal

  # ---------- API GATEWAY ----------
  api-gateway:
    image: nginx:latest
    container_name: api_gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      backend:
        condition: service_healthy
      users-api:
        condition: service_healthy
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  db_main_data:
  db_users_data:
