"""create subscribers table

Revision ID: b321560e5405
Revises: efae4600d8d4
Create Date: 2026-01-09 04:00:26.114680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b321560e5405'
down_revision: Union[str, Sequence[str], None] = 'efae4600d8d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscriber_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscriber_id', 'author_id', name='ux_sub')
    )
    op.create_index(op.f('ix_subscribers_author_id'), 'subscribers', ['author_id'], unique=False)
    op.create_index(op.f('ix_subscribers_subscriber_id'), 'subscribers', ['subscriber_id'], unique=False)
    op.alter_column('users', 'subscription_key',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "users",
    sa.Column("subscription_key", sa.Text(), nullable=True)
    )
    op.drop_index(op.f('ix_subscribers_subscriber_id'), table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_author_id'), table_name='subscribers')
    op.drop_table('subscribers')
    # ### end Alembic commands ###
